#!/bin/sh 


iptables --flush 

#Block puerto http
#iptables -A INPUT -p tcp --dport 80 -j DROP


#configuramos tarjeta de red para eth0:1
ifconfig eth1:2 181.181.1.2 netmask 255.255.255.0
ifconfig eth1:1 181.181.2.1 netmask 255.255.255.0

#Soporte de IP Forwarding en el kernel
echo 1 > /proc/sys/net/ipv4/ip_forward

#permite el paso de la informacion entre las dos redes
iptables -A INPUT -i eth1 -j ACCEPT
#define las reglas de enmascaramiento en la tarjeta que brinda conexion
iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE
iptables -A FORWARD -i eth1 -j ACCEPT

exec /etc/init.d/dhcp3-server start

