<? 
$vector = array( 
1 => "LO QUE DEBEMOS APRENDER A HACER LO APRENDEMOS HACIENDOLO", 
2 => "SI BUSCAS RESULTADOS DISTINTOS NUNCA HAGAS LO MISMO", 
3 => "PAMELA ES UNA DOG", 
4 => "COROMOTO ES UNA BRUJILDA", 
5 => "ESTO ESTA QUEDANDO BIEN",
); 
$numero = rand(1,5); 
echo "ESTA ES UNA FRACE ALEATORIA: "."$vector[$numero]"."\n"; 
?>
